version: '3.8'

services:
  dzoms-keycloak-postgres:
    image: postgres:16.1
    container_name: dzoms_keycloak_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dzoms_keycloak_db
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - dzoms-keycloak-net

  dzoms-keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: dzoms_keycloak
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: dzoms-keycloak-postgres
      KC_DB_URL_DATABASE: dzoms_keycloak_db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm-export.json
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    depends_on:
      - dzoms-keycloak-postgres
    networks:
      - dzoms-keycloak-net

networks:
  dzoms-keycloak-net:
    name: dzoms-keycloak-net