spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:/db/changelog.xml
  web:
    resources:
      add-mappings: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8282/realms/master
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: backend
            client-secret: AXJ3KTBDXCDvfxHtuOSfJ8boFsDytH0P
            scope: openid


server:
  port: 8082
  servlet:
    session:
      timeout: 30
  error:
    whitelabel:
      enabled: false
