spring:
  datasource:
    url: jdbc:postgresql://postgres:5435/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:/db/changelog.xml
  web:
    resources:
      add-mappings: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8282/realms/master

server:
  port: 8082
  error:
    whitelabel:
      enabled: false
